### ISSUE TITLE
 License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [dientuki/MMM-SystemInfo#1]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with a screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by dientuki** [comment]
Here you got! https://github.com/dientuki/MMM-SystemInfo/commit/4bef9898918741dddc8600dd752db980bfb16423

**Comment by KristjanESPERANTO** [comment]
Nice. Now your module looks nice on the new module list :rocket: :slightly_smiling_face:
